const axios = require('axios')
require('dotenv').config()
const app = require("../bot.js");
const { log } = require('../modules/log.js');
const {checkIfAPIAccess, checkIfProd} = require("../modules/apiAccess");
const {updateStats} = require("../modules/updateStats");

module.exports = async (client, guild) => {
	// This event triggers when the bot joins a guild.

	log(`New guild joined: ${guild.name} (id: ${guild.id}). This guild has ${guild.memberCount} members!`, "info")
	guild.members
		.fetch()
		.then((members) =>
			members.forEach((member) => {
				let user = member.user
				console.log(`${user.username} - ${user.id}`)
				axios({
					"method": "GET",
					"url": `${process.env.API_SERVER}/karen/profile/`,
					"headers": {
						"Authorization": process.env.AUTH_B64,
						"Content-Type": "application/json; charset=utf-8",
						'User-Agent': process.env.AUTH_USERAGENT
					},
					"auth": {
						"username": process.env.AUTH_USER,
						"password": process.env.AUTH_PASS
					},
					"params": {
						"id": user.id
					}
				}).then((response) => {
					// If success, return
					return
				}, (error) => {
					// If error (which means person doesn't have a profile), create one
					const profile = {
						description: "I am someone who got their profile auto generated by a bot",
						gender: "Not specified",
						birthday: "Not specified",
						country: "None",
						rank: "",
						languages: "None"
					}
					// Sends profile to server
					axios({
						"method": "POST",
						"url": `${process.env.API_SERVER}/karen/profile/`,
						"headers": {
							"Authorization": process.env.AUTH_B64,
							"Content-Type": "application/json; charset=utf-8",
							'User-Agent': process.env.AUTH_USERAGENT
						},
						"auth": {
							"username": process.env.AUTH_USER,
							"password": process.env.AUTH_PASS
						},
						"data": {
							profile,
							"id": user.id
						}
					})
				});
			}),
		);

	if (checkIfProd()) {
		updateStats(client)
	}
}